// <auto-generated />
namespace koinfast.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seed_packages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed_packages));
        
        string IMigrationMetadata.Id
        {
            get { return "202010041452506_seed_packages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
